[build]
  publish = "public"

[[redirects]]
  from = "/client"
  to = "/client/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/menu"
  to = "/menu.html"
  status = 200
