[build]
  publish = "public"

[[redirects]]
  from = "/client"
  to = "/client/index.html"
  status = 200

[[redirects]]
  from = "/platform"
  to = "/platform/index.html"
  status = 200

[[redirects]]
  from = "/restaurant"
  to = "/restaurant/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/restaurant/login.html"
  status = 200

[[redirects]]
  from = "/menu"
  to = "/menu.html"
  status = 200
